// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

public class CombatNodeFactory
{
	private BattleEntity mEntity;

	public BattleEntity entity {
		get { return mEntity; }
	}

	private CharacterCombatNode mCachedCharacterNode;

	public CombatNodeFactory (BattleEntity entity)
	{
		mEntity = entity;
	}

	public ICombatNode CreateWeaponConfigNode(int equipedWeaponIndex, bool isActiveWeapon) {
		IWeapon weapon = mEntity.equipedWeapons [equipedWeaponIndex];
		return CreateWeaponConfigNode (weapon, isActiveWeapon);
	}

	public ICombatNode CreateWeaponConfigNode(IWeapon config, bool isActiveWeapon) {
		return new WeaponCombatNode(config, isActiveWeapon);
	}

    public ICombatNode CreateArmorNode(int armorPosition) {
        IArmor armor = mEntity.character.equipedArmor[armorPosition];
        return new ArmorCombatNode(armor);
    }

	public ICombatNode CreateCharacterNode() {
		if (mCachedCharacterNode == null) {
			mCachedCharacterNode = new CharacterCombatNode(mEntity.character);
		}
		return mCachedCharacterNode;
	}

	public ICombatNode CreateStatusEffectNodes() {
		// map status effects to buff properties
		ConfigurableCombatNode configNode = new ConfigurableCombatNode();
		foreach(StatusEffectClient.StatusEffectSummary summary in mEntity.statusEffectClient.Summaries) {
			configNode.LoadStatusEffectProperty(summary.property, summary.netValue);
		}
		return configNode;
	}
}

