//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

public class WeaponCombatNode : EquipmentCombatNode
{
    private IWeapon mWeapon;

    /// <summary>
    /// if weapon is active weapon, we will include the damage scaling stats
    /// </summary>
    /// <param name="weapon"></param>
    /// <param name="isActiveWeapon"></param>
	public WeaponCombatNode(IWeapon weapon, bool isActiveWeapon) : base(weapon) {
        mWeapon = weapon;

        // 
        if (isActiveWeapon) {
            LoadAttributeScalar(mWeapon.AttributeScaling);
            LoadDamageMin(mWeapon.DamageMin);
            LoadDamageMax(mWeapon.DamageMax);
        }
	}
}

