//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using UnityEngine;

[Serializable]
public class SkillSO : SanitySO, ISkill
{
	public string displayName;
	public Texture2D icon;

	public string DisplayName {
		get {
			return displayName;
		}
	}

	protected override void SanityCheck ()
	{
		if(string.IsNullOrEmpty(displayName)) {
			LogNull("displayName");
		}

		if(icon == null) {
			LogNull("icon");
		}
	}
}

