//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

public enum TargetingType {
	SELF,
	ALL,
	SINGLE,
	ROW,
	SELF_ROW
}

public enum TargetStart {
	ENEMY,
	SELF,
	DEAD
}