// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using UnityEngine;

public class PartyComponent : MonoBehaviour
{
	protected List<Character> mCharacters;

	public List<Character> Characters {
		get { return new List<Character> (mCharacters); }
	}
}


