//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

public class EnemyCharacter : Character
{

	public EnemyCharacter (){	}

	private AISkillResolver skillResolver;
	public AISkillResolver SkillResolver {
		get { return skillResolver; }
	}

	public EnemyCharacter(EnemyCharacterSO config) : base(config) {
		skillResolver = new AISkillResolver(config.skillRules);
	}
	
}
