//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
public class GeneralOffensiveModifier
{
	public readonly GeneralOffensiveModifierType type;
	public readonly float modValue;
	
	public GeneralOffensiveModifier (GeneralOffensiveModifierType modType, float modValue)
	{
		this.type = modType;
		this.modValue = modValue;
	}
}

