//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
public enum GeneralOffensiveModifierType
{
	TOTAL_DMG_ADD,
	TOTAL_DMG_MULTIPLY,
	CRIT_CHANCE_ADD,
	CRIT_CHANCE_MULTIPLY,
}

