//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

public enum PhysicalOffensiveModifierType
{
	POWER_PHYSICAL_ADD,
	POWER_PHYSICAL_MULTIPLY,
	ARMOR_IGNORE_ADD,
	ARMOR_IGNORE_MULTIPLY,
	DODGE_IGNORE_ADD,
	DODGE_IGNORE_MULTIPLY,
	ACCURACY_ADD,
	ACCURACY_MULTIPLY
}
