//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

public class TargetLifeConditionSO : TargetConditionSO
{
	public bool isAlive = true;

	public override bool IsValidTarget (BattleEntity entity)
	{
		if(isAlive) {
			return entity.currentHP > 0;
		}
		else {
			return entity.currentHP <= 0;
		}
	}
}


