//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

/// <summary>
/// AI target filter. A class to check to make sure we are only looking at valid targets for this AI rule
/// </summary>
public class AITargetFilter : IAIFilter
{
	private AISkillRule.ConditionTarget mTargetParam;


	public AITargetFilter(AISkillRule.ConditionTarget target) {
		this.mTargetParam = target;
	}

	public void FilterEntities (BattleEntity sourceEntity, HashSet<BattleEntity> entities)
	{
		switch(mTargetParam) {
		case AISkillRule.ConditionTarget.ENEMY:
			entities.RemoveWhere(FilterEnemy);
			break;
		case AISkillRule.ConditionTarget.PC:
			entities.RemoveWhere(FilterPC);
			break;
		case AISkillRule.ConditionTarget.SELF:
			entities.RemoveWhere(delegate(BattleEntity obj) {
				return sourceEntity != obj;
			});
			break;
		}
	}

	public bool FilterPC(BattleEntity entity) {
		return !entity.isPC;
	}

	public bool FilterEnemy(BattleEntity entity) {
		return entity.isPC;
	}	
}

