//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using UnityEngine;

public interface IStatusEffectRunner : IStatusEffect
{
	BattleEntity sourceEntity {
		get;
	}

	/// <summary>
	/// Gets the total length of the duration. How long should it exist before it removes naturally
	/// </summary>
	/// <value>The total length of the duration.</value>
	float totalDurationLength {
		get;
	}	

	/// <summary>
	/// Gets the length of the current duration.
	/// </summary>
	/// <value>The length of the current duration.</value>
	float currentDurationLength {
		get;
	}

	bool isExpired {
		get;
	}

	/// <summary>
	/// Increments the duration time.
	/// </summary>
	/// <param name="timeDelta">Time delta.</param>
	void IncrementDurationTime(float timeDelta);	
}


