//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

public interface IStatusEffect
{
	StatusEffectProperty property {
		get;	
	}
	
	StatusEffectType type {
		get;
	}

	float strength {
		get;
	}

	float duration {
		get;
	}

	float capacity {
		get;
	}
}
