//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

[Serializable]
public class StatusEffectGroupGUIProperty
{
	// TODO add GET accessors when we start using this
	[SerializeField]
	private string mOnStartTextFormat;

	[SerializeField]
	private string mOnEndTextFormat;

	[SerializeField]
	private Texture2D mStatusIcon;
}

