//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;


public enum StatusEffectType
{
	POSITIVE,
	NEGATIVE,
	NULLIFY
}

public enum StatusEffectProperty
{
	NONE,
	
	// stat effects
	STR_MOD,
	VIT_MOD,
	AGI_MOD,
	DEX_MOD,
	INT_MOD,
	WIS_MOD,
	LUCK_MOD,
	
	// offensive effects
	CRIT_CHANCE,
	CRIT_POWER,
	SPELL_FAILURE,
	SPELL_DMG,
	HIT_CHANCE,
	PHYSICAL_DMG,
	
	
	// defensive effects
	SPELL_RESIST,
	HEALING_REDUCTION,
	CRIT_EVASION,
	
	// turn / speed effects 
	SPEED,
	FATIGUE_COST,
	LOSE_TURN ,
	
	HP_REGEN
	
	
	
	
	
	
}

