//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

public class StatusEffectRunner : IStatusEffectRunner
{
	private BattleEntity m_SourceEntity;
	private float m_TimeCounter;
	private IStatusEffect m_StatusEffect;

	public StatusEffectRunner(BattleEntity sourceEntity, IStatusEffect statusEffect) {
		m_SourceEntity = sourceEntity;
		m_StatusEffect = statusEffect;
	}

	public BattleEntity sourceEntity {
		get {
			return m_SourceEntity;
		}
	}

	public StatusEffectProperty property {
		get {
			return m_StatusEffect.property;
		}
	}

	public StatusEffectType type {
		get {
			return m_StatusEffect.type;
		}
	}

	public float strength {
		get {
			return m_StatusEffect.strength;
		}
	}

	public float duration {
		get {
			return m_StatusEffect.duration;
		}
	}

	public float capacity {
		get {
			return m_StatusEffect.capacity;
		}
	}

	public void IncrementDurationTime (float timeDelta)
	{
		m_TimeCounter += timeDelta;
	}
	

	public float totalDurationLength {
		get {
			return m_StatusEffect.duration;
		}
	}

	public float currentDurationLength {
		get {
			return m_TimeCounter;
		}
	}

	public bool isExpired {
		get {
			return m_TimeCounter >= m_StatusEffect.duration;
		}
	}
}


