//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

/// <summary>
/// StatusEffectGroup, there may be many different instances that cause the same effect. We want to make sure we 
/// associate each instant that shares a group with the same object for sake of asssigning text / graphic information
/// as well as applying multiple buffs of the same type.
/// 
/// </summary>
public class StatusEffectGroupSO : ScriptableObject
{
	// IF THIS IS A STAT GROUP, LETS SET IT HERE
	[SerializeField]
	private StatusEffectProperty mCombatProperty = StatusEffectProperty.NONE;
	// TODO special case status effect group: 
	// ie: poison, haste, onEvent()

	// GUI information 

	// icons
	[SerializeField]
	private StatusEffectGroupGUIProperty m_NegativeGUIProperty = null;

	[SerializeField]
	private StatusEffectGroupGUIProperty m_PositiveGUIProperty = null;
	


	// accessors
	public StatusEffectProperty statusEffectProperty {
		get { return mCombatProperty; }
	}

	public StatusEffectGroupGUIProperty negativeGUIProperty {
		get {
			return this.m_NegativeGUIProperty;
		}
	}

	public StatusEffectGroupGUIProperty positiveGUIProperty {
		get {
			return this.m_PositiveGUIProperty;
		}
	}

}


