// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;

[Serializable]
public class StatusEffectRule
{
	[SerializeField]
	private StatusEffectRuleTarget m_TargetRule;

	[SerializeField]
	private StatusEffectRuleHitPredicate m_HitPredicate;


	
	/// <summary>
	/// Gets the effect.
	/// </summary>
	/// <value>The effect.</value>
	public IStatusEffectRunner effect {
			get;
			private set;
	}

	/// <summary>
	/// Gets the rule.
	/// </summary>
	/// <value>The rule.</value>
	public StatusEffectRuleHitPredicate rule {
			get;
			private set;
	}



	public enum StatusEffectRuleTarget {
		TARGET,
		TARGET_ROW,
		TARGET_ALL,
		SELF,
		SELF_ROW,
		SELF_ALL
	}

	// Rules to determine when the effect should be proccessed
	public enum StatusEffectRuleHitPredicate {
		ALWAYS,
		ON_HIT,
		ON_MISS
	}
}