//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

[Serializable]
public class StatusEffectParams
{
	[SerializeField]
	private StatusEffectProperty m_Property;

	[SerializeField]
	private StatusEffectType m_Type;

	[SerializeField]
	private float m_Strength;

	[SerializeField]
	private float m_Duration;

	
	public StatusEffectProperty property {
		get {
			return this.m_Property;
		}
	}
	
	public StatusEffectType type {
		get {
			return this.m_Type;
		}
	}

	public float strength {
		get { return m_Strength; }
	}

	public float duration {
		get { return m_Duration; }
	}
}
