//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

public class StatusEffect : IStatusEffect
{
	public StatusEffect(StatusEffectParams p, BattleEntity source) {
		m_SourceEntity = source;
		m_Params = p;
	}

	private BattleEntity m_SourceEntity;
	private StatusEffectParams m_Params;
	
	public StatusEffectProperty property {
		get {
			return this.m_Params.property;
		}
	}
	
	public StatusEffectType type {
		get {
			return this.m_Params.type;
		}
	}

	public float strength {
		get { return m_Params.strength; }
	}

	public float duration {
		get { return m_Params.duration; }
	}

	public float capacity {
		get { return 10; } // TODO mitigate from character
	}
}
