//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

public class DeathEvent : IBattleEvent
{
	private BattleEntity mSrcEntity;

	public DeathEvent (BattleEntity entity)
	{
		mSrcEntity = entity;
	}

	public BattleEntity SrcEntity {
		get {
			return mSrcEntity;
		}
	}

	public BattleEventType EventType {
		get {
			return BattleEventType.DEATH;
		}
	}

	public override string ToString ()
	{
		return string.Format ("[DeathEvent: srcEntity={0}]", SrcEntity.character.displayName);
	}
}
