// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;

public class DodgeEvent : IBattleEvent
{
	private BattleEntity mSrcEntity;
	private BattleEntity mDestEntity;


	public DodgeEvent (BattleEntity srcEntity, BattleEntity destEntity)
	{
		mSrcEntity = srcEntity;
		mDestEntity = destEntity;
	}

	/// <summary>
	/// Gets the source entity. This is the attacker
	/// </summary>
	/// <value>The source entity.</value>
	public BattleEntity SrcEntity {
		get {
			return mSrcEntity;
		}
	}

	/// <summary>
	/// Gets the destination entity. This is the defender who dodged
	/// </summary>
	/// <value>The destination entity.</value>
	public BattleEntity destEntity {
		get {
			return mDestEntity;
		}
	}

	public BattleEventType EventType {
		get {
			return BattleEventType.DODGE;
		}
	}

	public override string ToString ()
	{
		return string.Format ("[DodgeEvent: mSrcEntity={0}, mDestEntity={1}]", mSrcEntity, mDestEntity);
	}
	
}

