//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
public class HealEvent : IBattleEvent
{
	private BattleEntity mSrcEntity;
	private BattleEntity mDestEntity;
	private float mHeal;
	private float mCritHeal;

	public HealEvent (BattleEntity srcEntity, BattleEntity destEntity, float heal, float critHeal) 
	{
		this.mSrcEntity = srcEntity;
		this.mDestEntity = destEntity;
		this.mHeal = heal;
		this.mCritHeal = critHeal;

	}

	public BattleEntity SrcEntity {
		get {
			return mSrcEntity;
		}
	}

	public BattleEventType EventType {
		get {
			return BattleEventType.MOVE;
		}
	}

	public BattleEntity destEntity {
		get {
			return mDestEntity;
		}
	}

	public float totalHeal {
		get {
			return mHeal + mCritHeal;
		}
	}

	public float heal {
		get {
			return mHeal;
		}
	}

	public float critHeal {
		get {
			return mCritHeal;
		}
	}

	public override string ToString ()
	{
		return string.Format ("[HealEvent: mSrcEntity={0}, mDestEntity={1}, mHeal={2}, mCritHeal={3}]", mSrcEntity, mDestEntity, mHeal, mCritHeal);
	}
	
}


