//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
public class PCMoveOperation
{
	// TODO flush out
	PCCharacter.RowPosition mSrcRow;
	PCCharacter.RowPosition mDestRow;

	PCBattleEntity mSrcEntity;

	public PCMoveOperation (PCBattleEntity srcEntity, PCCharacter.RowPosition destRow) 
	{
		this.mSrcEntity = srcEntity;
		this.mSrcRow = srcEntity.pcCharacter.rowPosition;
		this.mDestRow = destRow;
	}

	public IBattleEvent Execute ()
	{
		// need to animate this?
		mSrcEntity.pcCharacter.rowPosition = mDestRow;
		return new MoveEvent (mSrcEntity, mSrcRow, mDestRow);
	}

	public BattleEntity srcEntity {
		get {
			return srcEntity;
		}
	}

	public BattleEventType eventType {
		get {
			return BattleEventType.MOVE;
		}
	}
}


