//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

public abstract class Equipment : IEquipment
{
	public string displayName;
	public Texture2D icon;

    // elemental offense and defense abilities
    public ElementVector offenseScalar = new ElementVector();
    public ElementVector defenseScalar = new ElementVector();

    // attribute bonuses
    public AttributeVector attributeExtra = new AttributeVector();

    // allow user to wear
    public EquipmentRestriction equipmentRestriction = new EquipmentRestriction();


	public string DisplayName {
		get {
			return displayName;
		}
	}

	public Texture2D Icon {
		get {
			return icon;
		}
	}

    public ElementVector OffensiveScalar {
        get { return offenseScalar; }
    }

    public ElementVector DefensiveScalar {
        get { return defenseScalar; }
    }

    public AttributeVector AttributeExtra {
        get { return attributeExtra; }
    }
}


