//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

public enum WeaponType
{
	DAGGER,
	SWORD,
	GREAT_SWORD,
	GAUNTLETS,
	AXE,
	MACE,
	SPEAR,
	BOW,
	CROSSBOW,
	GUN,
	STAVE,
	ROD,
	WAND,
	COUNT
}
