//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

public interface IBattleEntityWeapon
{
	float baseDamage {
		get;
	}

	PhysicalOffensiveModifier[] offensiveModifiers {
		get; // todo move this to physical weapon mod
	}

	StatModifier [] statModifiers {
		get;
	}

	DamageType dmgType {
		get;
	}

	WeaponType weaponType {
		get;
	}
}

