//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
public class TextUtils
{
	public static string DmgToString(DamageType dmg) {
		switch(dmg) {
		case DamageType.CRUSH:
			return "crush";
		case DamageType.SLASH:
			return "slash";
		case DamageType.PIERCE:
			return "pierce";
		case DamageType.DARK:
			return "dark";
		case DamageType.LIGHT:
			return "light";
		case DamageType.WIND:
			return "wind";
		case DamageType.EARTH:
			return "earth";
		case DamageType.FIRE:
			return "fire";
		case DamageType.WATER:
			return "water";
		}
		return "";
	}


}

