//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
public interface IBattleAction
{
	/// <summary>
	/// Important to note action clock should always be called even when the delta time has passed.
	/// the action time threshold, it will be called one last time
	/// </summary>
	/// <param name="actionClock">Action clock.</param>
	void OnExecuteAction(float actionClock);

	float timePrepare { get; }
	float timeAction { get; }
	float timeRecover { get; }
}


