//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

public enum ResolvedTargetEnum
{
	SINGLE,
	ENEMY_ALL,
	ALLY_ALL,
	ALLY_ROW_FRONT,
	ALLY_ROW_MIDDLE,
	ALLY_ROW_BACK,
	SELF_ROW,
	SELF
}

