//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

public class SelectableTarget
{
	public readonly string targetName;
	public readonly List<BattleEntity> entities;
	public readonly ResolvedTargetEnum resolvedTargetType;

	public SelectableTarget (string targetName, List<BattleEntity> entities, ResolvedTargetEnum resolvedTargetType)
	{
		this.targetName = targetName;
		this.entities = entities;
		this.resolvedTargetType = resolvedTargetType;
	}
}

