//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using UnityEngine.UI;

public class DebugStatusEffectGUIComponent : MonoBehaviour {

	[SerializeField]
	private Slider m_TimeSlider;

	[SerializeField]
	private Text m_Text;

	private IStatusEffectRunner m_Runner;

	public IStatusEffectRunner runner { 
		get { return m_Runner; } 
		set {
			m_Runner = value;
			if(value != null) {
				m_TimeSlider.minValue = 0;
				m_TimeSlider.maxValue = value.duration;
			}
		} 
	}

	void OnGUI() {
		if(runner != null) {
			m_Text.text = string.Format("{0}: {1} ({2}/{3})", 
			                       runner.property.ToString(), 
			                       runner.strength,
			                       runner.duration - runner.currentDurationLength,
			                       runner.duration);

			m_TimeSlider.value = runner.duration - runner.currentDurationLength;
		}
		else {
			m_Text.text = "Not connected";
			m_TimeSlider.value = 0;
		}
	}
}